#
#	Makefile for all codes
#
#
all:
	cd 3Dray      && make 			&& cd ..
	cd ttimes     && make ttimes 	&& cd ..
	cd GRT        && make findpath1 && cd ..
	
clean:
	cd ttimes     && make clean 	&& cd ..
	cd GRT        && make clean 	&& cd ..
